name: PencilCraft
version: beta-0.2
main: com.brumisharuma.pencilcraft.PencilCraft

depend:
  - ProtocolLib

commands:
  pencil:
    description: Gives you the pencil item.
    usage: /pencil
  undo:
    description: Undoes the last 60 seconds of action performed with the pencil.
    usage: /undo