name: BetterStopV2
version: 2.0
main: com.TinyHoe.betterstop.BetterStopV2
author: TinyHoe

commands:
  stop:
    description: Starts the shutdown countdown
    permission: betterstop.admin

  stopcancel:
    description: Cancels the shutdown countdown
    permission: betterstop.admin

  forcestop:
    description: Stops the server immediately
    permission: betterstop.admin

  betterstop:
    description: BetterStop main command

permissions:
  betterstop.admin:
    default: op